name: Deploy to VPS

on:
  workflow_dispatch:
  push:
    branches:
      - principal

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Server via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "*,.*" # Copia todos os arquivos, incluindo os ocultos
          target: ${{ secrets.TARGET_DIR }}
          overwrite: true
